### PR TITLE
Fix stop() after start()

### LINKED ISSUE #46: `Monitor.restart` sets `forceRestart`, but doesn't unset it on restart
Attempting to stop a script after it has been restarted at least once causes the script to become unstoppable until `.start()` is called again.

[Line 306](https://github.com/nodejitsu/forever-monitor/blob/master/lib/forever-monitor/monitor.js#L306) of `monitor.js` shows that `forceRestart` is set to true before the child process is killed.

I see that [line 175](https://github.com/nodejitsu/forever-monitor/blob/master/lib/forever-monitor/monitor.js#L175) of the same file has `forceRestart` being set to false, but I don't believe this is called (is it related?) unless `.start()` is called explicitly.

So essentially, after restarting a script, I cannot stop it anymore, as it starts right back up again.

### PR DESCRIPTION
**Pull request by carter-thaxton**
Fixes #46 
I added to one of the tests, which would reproduce the buggy behavior, and indeed this fixes it.

### CODE REVIEW

File: test/monitor/start-stop-test.js [hunk 1]
```diff
@@ -52,7 +53,13 @@ vows.describe('forever-monitor/monitor/start-stop').addBatch({
               child.once("restart", function(){
                 child.stop()
               })
-              child.once("exit", function(){ that.callback(null, child) })
+              child.once("exit", function(){
+                // wait another two seconds, to make sure the child is not restarted after calling stop()
+                setTimeout(function() {
+                  clearTimeout(timer)
```
Comment (carter-thaxton) [inline test/monitor/start-stop-test.js]: This test had an additional issue, which was that it wasn't clearing the above timer on success, nor was it declaring `timer` as a `var`.
